"use client";

import { useCallback, useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { zodResolver } from "@hookform/resolvers/zod";
import { createColumnHelper, createPaginatedRowModel, flexRender, rowPaginationFeature, tableFeatures, useTable } from "@tanstack/react-table";
import { CalendarDays, Check, Circle, Columns3, List, LoaderCircle, MoreHorizontal, Pencil, Plus, Search, Trash2, UserRound } from "lucide-react";
import { Controller, useForm } from "react-hook-form";
import { toast } from "sonner";

import { changeTaskPriorityAction, changeTaskStatusAction, createTaskAction, deleteTaskAction, updateTaskAction } from "@/app/(dashboard)/tareas/actions";
import { EmptyState } from "@/components/shared/empty-state";
import { useFormattingPreferences } from "@/components/providers/formatting-provider";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogMedia, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Button, buttonVariants } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { AppSelect } from "@/components/shared/app-select";
import { formatDate } from "@/lib/formatting";
import { taskFormSchema, type TaskFormInput } from "@/lib/validations/tasks";
import { TASK_PRIORITIES, TASK_PRIORITY_LABELS, TASK_STATUSES, TASK_STATUS_LABELS, type TaskListItem, type TaskOptions, type TaskPriority, type TaskStatus } from "@/types/task";

const priorityStyles: Record<TaskPriority, string> = { low: "bg-muted text-muted-foreground", medium: "bg-status-info/10 text-status-info", high: "bg-status-warning/10 text-status-warning", urgent: "bg-destructive/10 text-destructive" };
const emptyForm: TaskFormInput = { project_id: "", title: "", description: "", assigned_to: "", status: "todo", priority: "medium", start_date: "", due_date: "" };

function toForm(task?: TaskListItem): TaskFormInput { return task ? { project_id: task.project_id ?? "", title: task.title, description: task.description ?? "", assigned_to: task.assigned_to ?? "", status: task.status, priority: task.priority, start_date: task.start_date ?? "", due_date: task.due_date ?? "" } : emptyForm; }
function PriorityBadge({ priority }: { priority: TaskPriority }) { return <span className={`rounded-full px-2 py-1 text-xs font-medium ${priorityStyles[priority]}`}>{TASK_PRIORITY_LABELS[priority]}</span>; }

function TaskDialog({ open, onOpenChange, task, options, canAssign, fixedProjectId }: { open: boolean; onOpenChange: (open: boolean) => void; task?: TaskListItem; options: TaskOptions; canAssign: boolean; fixedProjectId?: string }) {
  const router = useRouter(); const [pending, startTransition] = useTransition();
  const { register, handleSubmit, control, formState: { errors } } = useForm<TaskFormInput>({ resolver: zodResolver(taskFormSchema), values: { ...toForm(task), project_id: fixedProjectId ?? toForm(task).project_id } });
  const submit = handleSubmit((values) => startTransition(async () => {
    const result = task ? await updateTaskAction(task.id, values) : await createTaskAction(values);
    if (!result.ok) { toast.error(result.error); return; }
    toast.success(task ? "Tarea actualizada." : "Tarea creada."); onOpenChange(false); router.refresh();
  }));
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{task ? "Editar tarea" : "Nueva tarea"}</DialogTitle><DialogDescription>Define el trabajo, su prioridad y las fechas operativas.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-5">
    <Label className="flex flex-col items-stretch gap-2 text-sm font-medium"><span>Título</span><Input {...register("title")} aria-invalid={!!errors.title} />{errors.title && <span className="text-xs text-destructive">{errors.title.message}</span>}</Label>
    <Label className="flex flex-col items-stretch gap-2 text-sm font-medium"><span>Descripción</span><Textarea {...register("description")} /></Label>
    <div className="grid gap-4 sm:grid-cols-2">
      {!fixedProjectId && <Label className="flex flex-col items-stretch gap-2 text-sm font-medium"><span>Proyecto</span><Controller name="project_id" control={control} render={({ field }) => <AppSelect value={field.value} onValueChange={field.onChange} emptyLabel="Sin proyecto" options={options.projects.map((item) => ({ value: item.id, label: item.name }))} />} /></Label>}
      <Label className="flex flex-col items-stretch gap-2 text-sm font-medium"><span>Responsable</span><Controller name="assigned_to" control={control} render={({ field }) => <AppSelect value={field.value} onValueChange={field.onChange} disabled={!canAssign} emptyLabel="Sin asignar" options={options.users.map((item) => ({ value: item.id, label: item.full_name }))} />} />{!canAssign && <span className="block text-xs font-normal text-muted-foreground">Solo un administrador puede cambiar la asignación.</span>}</Label>
      <Label className="flex flex-col items-stretch gap-2 text-sm font-medium"><span>Estado</span><Controller name="status" control={control} render={({ field }) => <AppSelect value={field.value} onValueChange={field.onChange} options={TASK_STATUSES.map((value) => ({ value, label: TASK_STATUS_LABELS[value] }))} />} /></Label>
      <Label className="flex flex-col items-stretch gap-2 text-sm font-medium"><span>Prioridad</span><Controller name="priority" control={control} render={({ field }) => <AppSelect value={field.value} onValueChange={field.onChange} options={TASK_PRIORITIES.map((value) => ({ value, label: TASK_PRIORITY_LABELS[value] }))} />} /></Label>
      <Label className="flex flex-col items-stretch gap-2 text-sm font-medium"><span>Fecha de inicio</span><Input type="date" {...register("start_date")} /></Label>
      <Label className="flex flex-col items-stretch gap-2 text-sm font-medium"><span>Fecha límite</span><Input type="date" {...register("due_date")} aria-invalid={!!errors.due_date} />{errors.due_date && <span className="text-xs text-destructive">{errors.due_date.message}</span>}</Label>
    </div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button><Button type="submit" disabled={pending}>{pending ? <LoaderCircle className="animate-spin" /> : <Check />}{task ? "Guardar" : "Crear tarea"}</Button></DialogFooter>
  </form></DialogContent></Dialog>;
}

function TaskActions({ task, canDelete, onEdit }: { task: TaskListItem; canDelete: boolean; onEdit: () => void }) {
  const router = useRouter(); const [confirm, setConfirm] = useState(false); const [pending, startTransition] = useTransition();
  const remove = () => startTransition(async () => { const result = await deleteTaskAction(task.id); if (!result.ok) { toast.error(result.error); return; } toast.success("Tarea eliminada."); setConfirm(false); router.refresh(); });
  return <><DropdownMenu><DropdownMenuTrigger render={<button type="button" className={buttonVariants({ variant: "ghost", size: "icon-sm" })} aria-label={`Acciones para ${task.title}`} />}><MoreHorizontal /></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={onEdit}><Pencil />Editar</DropdownMenuItem>{canDelete && <><DropdownMenuSeparator /><DropdownMenuItem variant="destructive" onClick={() => setConfirm(true)}><Trash2 />Eliminar</DropdownMenuItem></>}</DropdownMenuContent></DropdownMenu>
  <AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogHeader><AlertDialogMedia><Trash2 /></AlertDialogMedia><AlertDialogTitle>¿Eliminar esta tarea?</AlertDialogTitle><AlertDialogDescription>Esta operación no se puede deshacer.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction variant="destructive" disabled={pending} onClick={remove}>Eliminar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}

const features = tableFeatures({ rowPaginationFeature, paginatedRowModel: createPaginatedRowModel() });
const columnHelper = createColumnHelper<typeof features, TaskListItem>();

export function TaskWorkspace({ tasks, options, currentUserId, canCreate, canAssign, canDelete, fixedProjectId, initialCreate = false }: { tasks: TaskListItem[]; options: TaskOptions; currentUserId: string; canCreate: boolean; canAssign: boolean; canDelete: boolean; fixedProjectId?: string; initialCreate?: boolean }) {
  const formatting = useFormattingPreferences();
  const router = useRouter(); const [view, setView] = useState<"list" | "kanban">("list"); const [mine, setMine] = useState(false); const [search, setSearch] = useState(""); const [project, setProject] = useState(fixedProjectId ?? ""); const [assignee, setAssignee] = useState(""); const [status, setStatus] = useState(""); const [priority, setPriority] = useState(""); const [date, setDate] = useState(""); const [dialogOpen, setDialogOpen] = useState(initialCreate && canCreate); const [editing, setEditing] = useState<TaskListItem>(); const [pending, startTransition] = useTransition();
  const filtered = useMemo(() => tasks.filter((task) => (!mine || task.assigned_to === currentUserId) && (!search || task.title.toLocaleLowerCase("es").includes(search.toLocaleLowerCase("es"))) && (!project || task.project_id === project) && (!assignee || task.assigned_to === assignee) && (!status || task.status === status) && (!priority || task.priority === priority) && (!date || task.due_date === date)), [tasks, mine, currentUserId, search, project, assignee, status, priority, date]);
  const mutateStatus = useCallback((task: TaskListItem, next: TaskStatus) => startTransition(async () => { const result = await changeTaskStatusAction(task.id, next); if (!result.ok) { toast.error(result.error); return; } toast.success(next === "completed" ? "Tarea completada." : "Estado actualizado."); router.refresh(); }), [router]);
  const mutatePriority = useCallback((task: TaskListItem, next: TaskPriority) => startTransition(async () => { const result = await changeTaskPriorityAction(task.id, next); if (!result.ok) { toast.error(result.error); return; } toast.success("Prioridad actualizada."); router.refresh(); }), [router]);
  const openEdit = useCallback((task: TaskListItem) => { setEditing(task); setDialogOpen(true); }, []);
  const columns = useMemo(() => columnHelper.columns([
    columnHelper.accessor("title", { header: "Tarea", cell: ({ row }) => <div><p className="font-medium">{row.original.title}</p><p className="mt-0.5 text-xs text-muted-foreground">{row.original.project_name ?? "Sin proyecto"}</p></div> }),
    columnHelper.accessor("assigned_to", { header: "Responsable", cell: ({ row }) => <span>{row.original.assignee_name ?? "Sin asignar"}</span> }),
    columnHelper.accessor("priority", { header: "Prioridad", cell: ({ row }) => <AppSelect ariaLabel={`Prioridad de ${row.original.title}`} value={row.original.priority} onValueChange={(value) => mutatePriority(row.original, value as TaskPriority)} options={TASK_PRIORITIES.map((value) => ({ value, label: TASK_PRIORITY_LABELS[value] }))} size="sm" className="w-28" /> }),
    columnHelper.accessor("due_date", { header: "Fecha límite", cell: ({ getValue }) => formatDate(getValue(), formatting) }),
    columnHelper.accessor("status", { header: "Estado", cell: ({ row }) => <AppSelect ariaLabel={`Estado de ${row.original.title}`} value={row.original.status} onValueChange={(value) => mutateStatus(row.original, value as TaskStatus)} options={TASK_STATUSES.map((value) => ({ value, label: TASK_STATUS_LABELS[value] }))} size="sm" className="w-32" /> }),
    columnHelper.display({ id: "actions", cell: ({ row }) => <TaskActions task={row.original} canDelete={canDelete} onEdit={() => openEdit(row.original)} /> }),
  ]), [canDelete, formatting, mutatePriority, mutateStatus, openEdit]);
  const table = useTable({ features, data: filtered, columns });
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-lg border p-1"><Button size="sm" variant={!mine ? "secondary" : "ghost"} onClick={() => setMine(false)}>Todas</Button><Button size="sm" variant={mine ? "secondary" : "ghost"} onClick={() => setMine(true)}><UserRound />Mis tareas</Button></div><div className="flex gap-2"><div className="flex rounded-lg border p-1"><Button size="icon-sm" variant={view === "list" ? "secondary" : "ghost"} onClick={() => setView("list")} aria-label="Vista lista"><List /></Button><Button size="icon-sm" variant={view === "kanban" ? "secondary" : "ghost"} onClick={() => setView("kanban")} aria-label="Vista kanban"><Columns3 /></Button></div>{canCreate && <Button onClick={() => { setEditing(undefined); setDialogOpen(true); }}><Plus />Nueva tarea</Button>}</div></div>
    <div className="grid gap-2 md:grid-cols-3 xl:grid-cols-6"><div className="relative md:col-span-2 xl:col-span-1"><Search className="absolute top-1/2 left-3 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar…" aria-label="Buscar tareas" className="pl-9" /></div>{!fixedProjectId && <AppSelect ariaLabel="Filtrar tareas por proyecto" value={project} onValueChange={setProject} emptyLabel="Todos los proyectos" options={options.projects.map((item) => ({ value: item.id, label: item.name }))} className="w-full min-w-0" />}<AppSelect ariaLabel="Filtrar tareas por responsable" value={assignee} onValueChange={setAssignee} emptyLabel="Responsables" options={options.users.map((item) => ({ value: item.id, label: item.full_name }))} className="w-full min-w-0" /><AppSelect ariaLabel="Filtrar tareas por estado" value={status} onValueChange={setStatus} emptyLabel="Estados" options={TASK_STATUSES.map((value) => ({ value, label: TASK_STATUS_LABELS[value] }))} className="w-full min-w-0" /><AppSelect ariaLabel="Filtrar tareas por prioridad" value={priority} onValueChange={setPriority} emptyLabel="Prioridades" options={TASK_PRIORITIES.map((value) => ({ value, label: TASK_PRIORITY_LABELS[value] }))} className="w-full min-w-0" /><Input type="date" value={date} onChange={(e) => setDate(e.target.value)} aria-label="Filtrar por fecha límite" /></div>
    {filtered.length === 0 ? <EmptyState icon={Circle} title={mine ? "No tienes tareas asignadas" : "No hay tareas para mostrar"} description="Crea una tarea o ajusta los filtros seleccionados." /> : view === "list" ? <div className="overflow-hidden rounded-xl border bg-card"><Table className="min-w-[780px]"><TableHeader className="bg-muted/40 text-xs uppercase text-muted-foreground">{table.getHeaderGroups().map((group) => <TableRow key={group.id}>{group.headers.map((header) => <TableHead key={header.id} className="px-4">{header.isPlaceholder ? null : flexRender(header.column.columnDef.header, header.getContext())}</TableHead>)}</TableRow>)}</TableHeader><TableBody>{table.getRowModel().rows.map((row) => <TableRow key={row.id}>{row.getAllCells().map((cell) => <TableCell key={cell.id} className="px-4">{flexRender(cell.column.columnDef.cell, cell.getContext())}</TableCell>)}</TableRow>)}</TableBody></Table></div> : <div className="grid gap-4 lg:grid-cols-3">{TASK_STATUSES.map((columnStatus) => <section key={columnStatus} className="rounded-xl border bg-muted/20 p-3"><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-semibold">{TASK_STATUS_LABELS[columnStatus]}</h3><span className="rounded-full bg-background px-2 py-0.5 text-xs text-muted-foreground">{filtered.filter((task) => task.status === columnStatus).length}</span></div><div className="space-y-3">{filtered.filter((task) => task.status === columnStatus).map((task) => <article key={task.id} className="rounded-lg border bg-card p-3"><div className="flex items-start justify-between gap-2"><Button variant="link" className="h-auto justify-start p-0 text-left" onClick={() => openEdit(task)}>{task.title}</Button><TaskActions task={task} canDelete={canDelete} onEdit={() => openEdit(task)} /></div><p className="mt-1 text-xs text-muted-foreground">{task.project_name ?? "Sin proyecto"}</p><div className="mt-4 flex items-center justify-between"><PriorityBadge priority={task.priority} /><span className="flex items-center gap-1 text-xs text-muted-foreground"><CalendarDays className="size-3.5" />{formatDate(task.due_date, formatting)}</span></div><div className="mt-3 flex items-center justify-between gap-3 border-t pt-3"><span className="text-xs text-muted-foreground">{task.assignee_name ?? "Sin asignar"}</span><AppSelect ariaLabel={`Estado de ${task.title}`} value={task.status} onValueChange={(value) => mutateStatus(task, value as TaskStatus)} disabled={pending} options={TASK_STATUSES.map((value) => ({ value, label: TASK_STATUS_LABELS[value] }))} size="sm" className="w-32" /></div></article>)}</div></section>)}</div>}
    <TaskDialog open={dialogOpen} onOpenChange={setDialogOpen} task={editing} options={options} canAssign={canAssign} fixedProjectId={fixedProjectId} />
  </div>;
}
