"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { CalendarPlus, FolderKanban, ListTodo, Search, UserRoundPlus, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList, CommandSeparator } from "@/components/ui/command";
import { hasPermission, PERMISSIONS } from "@/lib/permissions";
import type { UserRole } from "@/types/auth";

type SearchResults = { projects: Array<{ id: string; name: string; code: string }>; clients: Array<{ id: string; name: string; company: string | null }>; tasks: Array<{ id: string; title: string; project_id: string | null; projects: { name: string } | null }> };
const empty: SearchResults = { projects: [], clients: [], tasks: [] };

export function GlobalSearch({ role }: { role: UserRole }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [query, setQueryState] = useState(""); const [results, setResults] = useState<SearchResults>(empty); const [loading, setLoading] = useState(false);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setOpen((value) => !value); } }; document.addEventListener("keydown", handler); return () => document.removeEventListener("keydown", handler); }, []);
  useEffect(() => { if (query.trim().length < 2) return; const controller = new AbortController(); const timeout = window.setTimeout(async () => { try { const response = await fetch(`/api/search?q=${encodeURIComponent(query.trim())}`, { signal: controller.signal }); if (response.ok) setResults(await response.json() as SearchResults); } catch { /* Cancelled when the query changes. */ } finally { if (!controller.signal.aborted) setLoading(false); } }, 300); return () => { window.clearTimeout(timeout); controller.abort(); }; }, [query]);
  const setQuery = (value: string) => { setQueryState(value); setResults(empty); setLoading(value.trim().length >= 2); };
  const go = (href: string) => { setOpen(false); setQuery(""); router.push(href); };
  const noResults = results.projects.length + results.clients.length + results.tasks.length === 0;
  return <><Button type="button" variant="outline" onClick={() => setOpen(true)} aria-label="Abrir búsqueda y paleta de comandos" className="hidden h-9 w-full max-w-64 justify-start bg-muted/40 px-3 text-muted-foreground md:flex"><Search className="size-4" /><span>Buscar...</span><kbd className="ml-auto rounded border border-black/20 bg-white px-1.5 py-0.5 font-mono text-[0.65rem] text-black dark:border-white/20 dark:bg-black dark:text-white">⌘ K</kbd></Button><Button type="button" variant="ghost" size="icon" aria-label="Buscar" className="md:hidden" onClick={() => setOpen(true)}><Search /></Button>
  <CommandDialog open={open} onOpenChange={setOpen}><CommandInput value={query} onValueChange={setQuery} placeholder="Buscar proyectos, clientes o tareas…" /><CommandList>{query.trim().length < 2 ? <><CommandGroup heading="Acciones rápidas">{hasPermission(role, PERMISSIONS.CREATE_PROJECTS) && <CommandItem onSelect={() => go("/proyectos/nuevo")}><FolderKanban />Crear proyecto</CommandItem>}<CommandItem onSelect={() => go("/clientes/nuevo")}><UserRoundPlus />Crear cliente</CommandItem><CommandItem onSelect={() => go("/tareas?nuevo=1")}><ListTodo />Crear tarea</CommandItem><CommandItem onSelect={() => go("/calendario?nuevo=1")}><CalendarPlus />Crear evento</CommandItem></CommandGroup></> : <>{loading && <p className="py-8 text-center text-sm text-muted-foreground">Buscando…</p>}{!loading && noResults && <CommandEmpty>No se encontraron resultados.</CommandEmpty>}{results.projects.length > 0 && <CommandGroup heading="Proyectos">{results.projects.map((item) => <CommandItem key={item.id} value={`project-${item.id}`} onSelect={() => go(`/proyectos/${item.id}`)}><FolderKanban /><div><p>{item.name}</p><p className="text-xs text-muted-foreground">{item.code}</p></div></CommandItem>)}</CommandGroup>}{results.clients.length > 0 && <><CommandSeparator /><CommandGroup heading="Clientes">{results.clients.map((item) => <CommandItem key={item.id} value={`client-${item.id}`} onSelect={() => go(`/clientes/${item.id}`)}><UsersRound /><div><p>{item.name}</p>{item.company && <p className="text-xs text-muted-foreground">{item.company}</p>}</div></CommandItem>)}</CommandGroup></>}{results.tasks.length > 0 && <><CommandSeparator /><CommandGroup heading="Tareas">{results.tasks.map((item) => <CommandItem key={item.id} value={`task-${item.id}`} onSelect={() => go("/tareas")}><ListTodo /><div><p>{item.title}</p><p className="text-xs text-muted-foreground">{item.projects?.name ?? "Sin proyecto"}</p></div></CommandItem>)}</CommandGroup></>}</>}</CommandList></CommandDialog></>;
}
