"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { zodResolver } from "@hookform/resolvers/zod";
import { CalendarClock, Check, CircleDollarSign, LoaderCircle, MoreHorizontal, Pencil, Plus, ReceiptText, Trash2, TrendingUp, TriangleAlert, WalletCards } from "lucide-react";
import { Controller, useForm } from "react-hook-form";
import { toast } from "sonner";

import { deleteExpenseAction, deletePaymentAction, saveExpenseAction, savePaymentAction } from "@/app/(dashboard)/finanzas/actions";
import { EmptyState } from "@/components/shared/empty-state";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogMedia, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Button, buttonVariants } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { AppSelect } from "@/components/shared/app-select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useFormattingPreferences } from "@/components/providers/formatting-provider";
import { formatCurrency, formatDate } from "@/lib/formatting";
import { expenseFormSchema, paymentFormSchema, type ExpenseFormInput, type PaymentFormInput } from "@/lib/validations/finances";
import { PAYMENT_STATUSES, PAYMENT_STATUS_LABELS, type FinanceData, type ProjectExpense, type ProjectPayment, type PaymentStatus } from "@/types/finance";

const statusStyles: Record<PaymentStatus, string> = { pending: "bg-status-warning/10 text-status-warning", paid: "bg-status-success/10 text-status-success", overdue: "bg-destructive/10 text-destructive", cancelled: "bg-muted text-muted-foreground" };

function PaymentDialog({ open, onOpenChange, payment, projects, fixedProjectId }: { open: boolean; onOpenChange: (value: boolean) => void; payment?: ProjectPayment; projects: FinanceData["projects"]; fixedProjectId?: string }) {
  const router = useRouter(); const [pending, startTransition] = useTransition();
  const values: PaymentFormInput = payment ? { project_id: payment.project_id, concept: payment.concept, amount: String(payment.amount), due_date: payment.due_date ?? "", paid_at: payment.paid_at?.slice(0, 10) ?? "", status: payment.status, notes: payment.notes ?? "" } : { project_id: fixedProjectId ?? "", concept: "", amount: "", due_date: "", paid_at: "", status: "pending", notes: "" };
  const { register, handleSubmit, control, formState: { errors } } = useForm<PaymentFormInput>({ resolver: zodResolver(paymentFormSchema), values });
  const submit = handleSubmit((input) => startTransition(async () => { const result = await savePaymentAction(payment?.id ?? null, input); if (!result.ok) { toast.error(result.error); return; } toast.success(payment ? "Pago actualizado." : "Pago programado."); onOpenChange(false); router.refresh(); }));
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>{payment ? "Editar pago" : "Nuevo pago"}</DialogTitle><DialogDescription>Registra un cobro recibido o programado. Los importes se expresan en soles.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2">{!fixedProjectId && <Label className="block space-y-2 text-sm font-medium sm:col-span-2"><span>Proyecto</span><Controller name="project_id" control={control} render={({ field }) => <AppSelect value={field.value} onValueChange={field.onChange} emptyLabel="Selecciona un proyecto" options={projects.map((project) => ({ value: project.id, label: project.name }))} />} /></Label>}<Label className="block space-y-2 text-sm font-medium sm:col-span-2"><span>Concepto</span><Input {...register("concept")} aria-invalid={!!errors.concept} /></Label><Label className="block space-y-2 text-sm font-medium"><span>Importe (S/)</span><Input inputMode="decimal" {...register("amount")} aria-invalid={!!errors.amount} />{errors.amount && <span className="block text-xs text-destructive">{errors.amount.message}</span>}</Label><Label className="block space-y-2 text-sm font-medium"><span>Estado</span><Controller name="status" control={control} render={({ field }) => <AppSelect value={field.value} onValueChange={field.onChange} options={PAYMENT_STATUSES.map((status) => ({ value: status, label: PAYMENT_STATUS_LABELS[status] }))} />} /></Label><Label className="block space-y-2 text-sm font-medium"><span>Vencimiento</span><Input type="date" {...register("due_date")} /></Label><Label className="block space-y-2 text-sm font-medium"><span>Fecha de pago</span><Input type="date" {...register("paid_at")} /><span className="block text-xs font-normal text-muted-foreground">Si está pagado y queda vacío, se usará la fecha actual.</span></Label><Label className="block space-y-2 text-sm font-medium sm:col-span-2"><span>Notas</span><Textarea {...register("notes")} /></Label></div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button><Button type="submit" disabled={pending}>{pending ? <LoaderCircle className="animate-spin" /> : <Check />}Guardar pago</Button></DialogFooter></form></DialogContent></Dialog>;
}

function ExpenseDialog({ open, onOpenChange, expense, projects, fixedProjectId }: { open: boolean; onOpenChange: (value: boolean) => void; expense?: ProjectExpense; projects: FinanceData["projects"]; fixedProjectId?: string }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const today = new Date().toISOString().slice(0, 10);
  const values: ExpenseFormInput = expense ? { project_id: expense.project_id, concept: expense.concept, amount: String(expense.amount), expense_date: expense.expense_date, notes: expense.notes ?? "" } : { project_id: fixedProjectId ?? "", concept: "", amount: "", expense_date: today, notes: "" };
  const { register, handleSubmit, control, formState: { errors } } = useForm<ExpenseFormInput>({ resolver: zodResolver(expenseFormSchema), values });
  const submit = handleSubmit((input) => startTransition(async () => { const result = await saveExpenseAction(expense?.id ?? null, input); if (!result.ok) { toast.error(result.error); return; } toast.success(expense ? "Gasto actualizado." : "Gasto registrado."); onOpenChange(false); router.refresh(); }));
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>{expense ? "Editar gasto" : "Nuevo gasto"}</DialogTitle><DialogDescription>Registra un gasto operativo asociado al proyecto.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2">{!fixedProjectId && <Label className="block space-y-2 text-sm font-medium sm:col-span-2"><span>Proyecto</span><Controller name="project_id" control={control} render={({ field }) => <AppSelect value={field.value} onValueChange={field.onChange} emptyLabel="Selecciona un proyecto" options={projects.map((project) => ({ value: project.id, label: project.name }))} />} /></Label>}<Label className="block space-y-2 text-sm font-medium sm:col-span-2"><span>Concepto</span><Input {...register("concept")} /></Label><Label className="block space-y-2 text-sm font-medium"><span>Importe (S/)</span><Input inputMode="decimal" {...register("amount")} aria-invalid={!!errors.amount} />{errors.amount && <span className="block text-xs text-destructive">{errors.amount.message}</span>}</Label><Label className="block space-y-2 text-sm font-medium"><span>Fecha</span><Input type="date" {...register("expense_date")} /></Label><Label className="block space-y-2 text-sm font-medium sm:col-span-2"><span>Notas</span><Textarea {...register("notes")} /></Label></div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button><Button type="submit" disabled={pending}>{pending ? <LoaderCircle className="animate-spin" /> : <Check />}Guardar gasto</Button></DialogFooter></form></DialogContent></Dialog>;
}

function RecordActions({ onEdit, onDelete, label }: { onEdit: () => void; onDelete: () => Promise<{ ok: boolean; error?: string }>; label: string }) {
  const router = useRouter(); const [confirm, setConfirm] = useState(false); const [pending, startTransition] = useTransition();
  const remove = () => startTransition(async () => { const result = await onDelete(); if (!result.ok) { toast.error(result.error ?? "No fue posible eliminar el registro."); return; } toast.success("Registro eliminado."); setConfirm(false); router.refresh(); });
  return <><DropdownMenu><DropdownMenuTrigger render={<button type="button" className={buttonVariants({ variant: "ghost", size: "icon-sm" })} aria-label={`Acciones para ${label}`} />}><MoreHorizontal /></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={onEdit}><Pencil />Editar</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem variant="destructive" onClick={() => setConfirm(true)}><Trash2 />Eliminar</DropdownMenuItem></DropdownMenuContent></DropdownMenu><AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogHeader><AlertDialogMedia><Trash2 /></AlertDialogMedia><AlertDialogTitle>¿Eliminar este registro?</AlertDialogTitle><AlertDialogDescription>Esta acción no se puede deshacer.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction variant="destructive" disabled={pending} onClick={remove}>Eliminar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}

export function FinanceWorkspace({ data, fixedProjectId }: { data: FinanceData; fixedProjectId?: string }) {
  const formatting = useFormattingPreferences();
  const money = (value: number) => formatCurrency(value, formatting);
  const date = (value: string | null) => formatDate(value?.slice(0, 10) ?? null, formatting);
  const [projectId, setProjectId] = useState(fixedProjectId ?? ""); const [paymentOpen, setPaymentOpen] = useState(false); const [expenseOpen, setExpenseOpen] = useState(false); const [editingPayment, setEditingPayment] = useState<ProjectPayment>(); const [editingExpense, setEditingExpense] = useState<ProjectExpense>();
  const filtered = useMemo(() => ({ projects: projectId ? data.projects.filter((item) => item.id === projectId) : data.projects, payments: projectId ? data.payments.filter((item) => item.project_id === projectId) : data.payments, expenses: projectId ? data.expenses.filter((item) => item.project_id === projectId) : data.expenses }), [data, projectId]);
  const totals = useMemo(() => { const fees = filtered.projects.reduce((sum, item) => sum + (item.fee ?? 0), 0); const paid = filtered.payments.filter((item) => item.status === "paid").reduce((sum, item) => sum + item.amount, 0); const expenses = filtered.expenses.reduce((sum, item) => sum + item.amount, 0); return { fees, paid, pending: Math.max(fees - paid, 0), expenses, percentage: fees > 0 ? Math.min(Math.round((paid / fees) * 100), 100) : 0 }; }, [filtered]);
  const overdue = filtered.payments.filter((item) => item.status === "overdue"); const upcoming = filtered.payments.filter((item) => item.status === "pending").slice(0, 5);
  const cards = [{ label: "Honorarios contratados", value: totals.fees, icon: WalletCards }, { label: "Total cobrado", value: totals.paid, icon: TrendingUp }, { label: "Total pendiente", value: totals.pending, icon: CalendarClock }, { label: "Gastos acumulados", value: totals.expenses, icon: ReceiptText }];
  return <div className="space-y-6">{!fixedProjectId && <div className="flex justify-end"><AppSelect ariaLabel="Filtrar finanzas por proyecto" value={projectId} onValueChange={setProjectId} emptyLabel="Todos los proyectos" options={data.projects.map((project) => ({ value: project.id, label: project.name }))} className="h-9 min-w-56" /></div>}
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, icon: Icon }) => <section key={label} className="rounded-xl border bg-card p-5"><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">{label}</p><Icon className="size-4 text-brand" /></div><p className="mt-3 text-2xl font-semibold">{money(value)}</p></section>)}</div>
  <section className="rounded-xl border bg-card p-5"><div className="flex justify-between text-sm"><span>Porcentaje cobrado</span><strong>{totals.percentage}%</strong></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-brand" style={{ width: `${totals.percentage}%` }} /></div></section>
  <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-xl border bg-card p-5"><div className="flex items-center gap-2"><CalendarClock className="size-4 text-brand" /><h2 className="font-semibold">Próximos pagos</h2></div><div className="mt-4 space-y-3">{upcoming.length ? upcoming.map((item) => <div key={item.id} className="flex justify-between gap-4 border-b pb-3 text-sm last:border-0"><div><p className="font-medium">{item.concept}</p><p className="text-xs text-muted-foreground">{item.project_name} · {date(item.due_date)}</p></div><strong>{money(item.amount)}</strong></div>) : <p className="text-sm text-muted-foreground">No hay pagos próximos.</p>}</div></section><section className="rounded-xl border bg-card p-5"><div className="flex items-center gap-2"><TriangleAlert className="size-4 text-destructive" /><h2 className="font-semibold">Pagos vencidos</h2></div><div className="mt-4 space-y-3">{overdue.length ? overdue.map((item) => <div key={item.id} className="flex justify-between gap-4 border-b pb-3 text-sm last:border-0"><div><p className="font-medium">{item.concept}</p><p className="text-xs text-muted-foreground">{item.project_name} · {date(item.due_date)}</p></div><strong className="text-destructive">{money(item.amount)}</strong></div>) : <p className="text-sm text-muted-foreground">No hay pagos vencidos.</p>}</div></section></div>
  <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Pagos</h2><Button onClick={() => { setEditingPayment(undefined); setPaymentOpen(true); }}><Plus />Nuevo pago</Button></div>{filtered.payments.length === 0 ? <EmptyState icon={CircleDollarSign} title="No hay pagos registrados" description="Programa el primer cobro del proyecto." /> : <div className="overflow-hidden rounded-xl border bg-card"><Table className="min-w-[700px]"><TableHeader className="bg-muted/40 text-xs uppercase text-muted-foreground"><TableRow>{["Concepto", "Proyecto", "Importe", "Vencimiento", "Estado", ""].map((heading, index) => <TableHead key={`${heading}-${index}`} className="px-4">{heading}</TableHead>)}</TableRow></TableHeader><TableBody>{filtered.payments.map((item) => <TableRow key={item.id}><TableCell className="px-4 font-medium">{item.concept}</TableCell><TableCell className="px-4">{item.project_name}</TableCell><TableCell className="px-4">{money(item.amount)}</TableCell><TableCell className="px-4">{date(item.due_date)}</TableCell><TableCell className="px-4"><span className={`rounded-full px-2.5 py-1 text-xs ${statusStyles[item.status]}`}>{PAYMENT_STATUS_LABELS[item.status]}</span></TableCell><TableCell className="px-4"><RecordActions label={item.concept} onEdit={() => { setEditingPayment(item); setPaymentOpen(true); }} onDelete={() => deletePaymentAction(item.id)} /></TableCell></TableRow>)}</TableBody></Table></div>}</section>
  <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Gastos</h2><Button variant="outline" onClick={() => { setEditingExpense(undefined); setExpenseOpen(true); }}><Plus />Nuevo gasto</Button></div>{filtered.expenses.length === 0 ? <EmptyState icon={ReceiptText} title="No hay gastos registrados" description="Registra los costos operativos del proyecto." /> : <div className="overflow-hidden rounded-xl border bg-card"><Table className="min-w-[650px]"><TableHeader className="bg-muted/40 text-xs uppercase text-muted-foreground"><TableRow>{["Concepto", "Proyecto", "Importe", "Fecha", ""].map((heading, index) => <TableHead key={`${heading}-${index}`} className="px-4">{heading}</TableHead>)}</TableRow></TableHeader><TableBody>{filtered.expenses.map((item) => <TableRow key={item.id}><TableCell className="px-4 font-medium">{item.concept}</TableCell><TableCell className="px-4">{item.project_name}</TableCell><TableCell className="px-4">{money(item.amount)}</TableCell><TableCell className="px-4">{date(item.expense_date)}</TableCell><TableCell className="px-4"><RecordActions label={item.concept} onEdit={() => { setEditingExpense(item); setExpenseOpen(true); }} onDelete={() => deleteExpenseAction(item.id)} /></TableCell></TableRow>)}</TableBody></Table></div>}</section>
  <PaymentDialog open={paymentOpen} onOpenChange={setPaymentOpen} payment={editingPayment} projects={data.projects} fixedProjectId={fixedProjectId} /><ExpenseDialog open={expenseOpen} onOpenChange={setExpenseOpen} expense={editingExpense} projects={data.projects} fixedProjectId={fixedProjectId} /></div>;
}
